# Generated by Django 5.2.7 on 2025-10-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='due_date',
        ),
    ]
