# Generated by Django 5.2.7 on 2025-10-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='encrypted_attachment',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='encrypted_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
