# Generated by Django 5.2.7 on 2025-10-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_attachment_remove_note_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='attachment_name',
        ),
        migrations.RemoveField(
            model_name='note',
            name='encrypted_attachment',
        ),
        migrations.RemoveField(
            model_name='note',
            name='encrypted_content',
        ),
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
