# Generated by Django 5.2.7 on 2025-10-16 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='notes.note')),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSchedule',
        ),
    ]
