# Generated by Django 5.2.7 on 2025-10-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_note_attachment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
