# Generated by Django 5.2.7 on 2025-10-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, db_column='content', null=True),
        ),
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='encrypted_content',
        ),
    ]
