# Generated by Django 5.2.7 on 2025-10-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_note_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='attachment',
        ),
        migrations.AddField(
            model_name='note',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='encrypted_attachment',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
