# Generated by Django 5.2.7 on 2025-10-31 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_task_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
    ]
