# Generated by Django 5.2.7 on 2025-10-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_attachment_note_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
